[command]
default=$CORE_ROOT_DIR/bin/tweak_iodef ; \
       =$CORE_ROOT_DIR/bin/tweak_iodef temporal_context.xml ; \
       =mkdir -p $CYLC_TASK_WORK_DIR/data ; \
       =lfs setstripe -c 32 -S 4m -p flash $CYLC_TASK_WORK_DIR/data ; \
       =module load nco ; \
       =echo "ncks --cnk_plc=nco --cnk_dmn=time,12 --cnk_dmn=dim2,$CHUNK_DIM_SIZE --dfl_lvl=4 /data/users/edward.hone/data/chunking/C224/qrclim.ozone_L70_O70.nc $CYLC_TASK_WORK_DIR/data/qrclim.ozone_L70_O70.nc" 1>&2 ; \
       =ncks --cnk_plc=nco --cnk_dmn=time,12 --cnk_dmn=dim2,$CHUNK_DIM_SIZE --dfl_lvl=4 /data/users/edward.hone/data/chunking/C224/qrclim.ozone_L70_O70.nc $CYLC_TASK_WORK_DIR/data/qrclim.ozone_L70_O70.nc ; \
       =$LAUNCH_SCRIPT/launch-exe

[file:iodef.xml]
mode=auto
source=$ROSE_SUITE_DIR/app/io_demo/file/iodef_temporal.xml

[namelist:extrusion]
number_of_layers=70

[namelist:files]
temporal_file_path='$CYLC_TASK_WORK_DIR/data/qrclim.ozone_L70_O70'

[namelist:io_demo]
temporal_reading=.true.

[namelist:timestepping]
dt=86400.0
